### PR TITLE
Added agent shape feature.

### PR DESCRIPTION
**Pull request by mikkleini**
Implemented feature request #25 
I used locally modified Viewer project to test it.
Would be nice to update Viewer project with agent shape selections and drawing, but not today.

### CODE REVIEW

**Comment by mikkleini** [comment]
Actually i forgot one thing - grid borders. Should keep required distance from that also.

**Comment by roy-t** [comment]
So cool that you've added this. I'm on vacation right now but back in a few days. Will take a look then 😁

**Comment by mikkleini** [comment]
Now the grid boundaries are taken into account also. Any part of agent can't get out of the grid. There was an easy but inefficient solution which would have required repeating calculations inside GetMovementOptions, so i created the boundary calculations once in path finding function.

With my first commit i broke the Viewer, now that's fixed as well.

**Comment by roy-t** [comment]
@mikkleini it looks great, I've merged it!

**Pull request merged**
