### PR TITLE
Partial path finding

### PR DESCRIPTION
**Pull request by mikkleini**
Solves #27 

If path to the end point is not found then at least a path to closest point is returned.
Introduced path finding result enumeration which explain the type of the path:

- PathFindResult.PathFound - Complete path found from start to end
- PathFindResult.PartialPathFound - Can't reach the end, but path to closest reachable point is returned
- PathFindResult.AlreadyAtTheEnd - Already at the end point
- PathFindResult.StartOutsideBoundaries - Start point or some part of agent is outside of map borders
- PathFindResult.EndOutsideBoundaries - End point is outside of map borders

However, this broke the compatibility. There's no more "GetPath" function, instead there's "TryGetPath".

Looks like this:
image

@roy-t  - please don't merge yet. I have some TODO's there.
I'm mainly thinking about removing agent shape dependent end point boundary check. It might be better to return partial path to end point rather than returning EndOutsideBoundaries error and no path.

### CODE REVIEW

**Comment by mikkleini** [comment]
Remove agent shape consideration from end point check. If agent is too large to get to the end which at the edge of grid then partial path is returned:

SquareW3 used in example:

image

**Comment by giulianob** [comment]
You could keep backwards compatibility with `GetPath`. Just add back `GetPath` and make it return null unless it finds a path?

**Comment by giulianob** [comment]
Also, what would happen if the agent is currently on top of a cell that is blocked? Is that what the "stuck" result is used for?

**Comment by roy-t** [comment]
Great work, I've re-implemented this in v2, which is under construction :).

**Pull request closed without merging**
